# Generated by Django 4.2 on 2026-04-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_message_groupmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="share_presence",
            field=models.BooleanField(default=True),
        ),
    ]
