# Generated by Django 4.2 on 2026-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_user_is_online_user_last_seen_user_share_presence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.CharField(
                blank=True, default="Hello Am on Emessage", max_length=255, null=True
            ),
        ),
    ]
